### PR TITLE
fix(`terraform_docs`): Fix issue and prioritize `output.file` setting from `.terraform-docs.yml` config over `--hook-config=--path-to-file=`

### LINKED ISSUE #697: `terraform_docs` generated output incorrect when `output.file` is configured
### Describe the bug

When `output.file` is specified, `terraform-docs` directly updates this file and prints the message: `README.md updated successfully` (or similar) to stdout. Because the `terraform_docs` hook always redirects stdout to the file, we end up with the below:

```md
<!-- BEGIN_TF_DOCS -->
README.md updated successfully
<!-- END_TF_DOCS -->
```

### How can we reproduce it?

in `.terraform-docs.yml`:

```yaml
output:
  file: "./README.md"
  # ... other settings as required
```

in `.pre-commit-config.yaml`:
```yaml
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.1
    hooks:
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
          - --hook-config=--use-standard-markers=true
```

### Environment information

* OS:  Windows 10

* `uname -a` and/or `systeminfo | Select-String "^OS"` output:

```bash
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
```

* Tools availability and versions:

```bash
GNU bash, version 5.2.26(1)-release (x86_64-pc-msys)
pre-commit 3.8.0
/usr/bin/bash: line 3: tofu: command not found
Terraform v1.5.5
Python 3.10.11
Python 3.10.11
checkov 3.2.223
infracost SKIPPED
terraform-docs version v0.18.0 228c7a7 windows/amd64
terragrunt SKIPPED
terrascan SKIPPED
TFLint version 0.52.0
+ ruleset.terraform (0.9.1)
+ ruleset.aws (0.32.0)
tfsec v1.28.10
trivy Version: 0.54.1
Check Bundle:
  Digest: sha256:ef2d9ad4fce0f933b20a662004d7e55bf200987c180e7f2cd531af631f408bb3
  DownloadedAt: 2024-08-15 02:35:34.5007199 +0000 UTC
tfupdate SKIPPED
hcledit SKIPPED
```

* `.pre-commit-config.yaml`:

<details><summary>file content</summary>

```yaml
# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.1
    hooks:
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
          - --hook-config=--use-standard-markers=true
```

</details>

### PR DESCRIPTION
**Pull request by sworisbreathing**
Put an `x` into the box if that apply:

- [ ] This PR introduces breaking change.
- [x] This PR fixes a bug.
- [ ] This PR adds new functionality.
- [ ] This PR enhances existing functionality.

### Description of your changes

This PR explicitly overrides any output files configured in `.terraform-docs.yml` to ensure the rendered documentation is written to stdout (which the hook pipes to a file and then injects into the appropriate destination file).

Fixes #697

### How can we test changes

setup as per the steps to reproduce in #697 and run the hook.

### CODE REVIEW

**Comment by MaxymVlasov** [comment]
This actually ignore any setting set in `.terraform-docs.yml` `output.file` 

Maybe that's a good idea to prioritize `.terraform-docs.yml` `output.file`  over  `- --hook-config=--path-to-file=` as it make step to resolve https://github.com/antonbabenko/pre-commit-terraform/issues/382

File: hooks/terraform_docs.sh [hunk 1]
```diff
@@ -159,13 +159,24 @@ function terraform_docs {
...
+    # Prioritize `.terraform-docs.yml` `output.file` over
+    # `--hook-config=--path-to-file=` if it set
+    local output_file
+    # Get latest non-commented `output.file` from `.terraform-docs.yml`
+    output_file=$(grep -A1000 -e '^output:$' "$config_file" | grep ' file:' | grep -v '#' | tail -n 1 || true)
+
+    if [ "$output_file" ]; then
+      # Extract filename from `output.file` line
+      text_file=$(echo "$output_file" | awk -F':' '{print $2}' | tr -d '[:space:]"' | tr -d "'")
+    fi
```
Comment (MaxymVlasov) [inline hooks/terraform_docs.sh:177]: Done it this way to avoid introduction of new dependencies (`yq`)

File: hooks/terraform_docs.sh [hunk 2]
```diff
@@ -159,13 +159,24 @@ function terraform_docs {
...
 
     local config_file=${args#*--config}
     config_file=${config_file#*=}
     config_file=${config_file% *}
 
+    # Prioritize `.terraform-docs.yml` `output.file` over
+    # `--hook-config=--path-to-file=` if it set
+    local output_file
+    # Get latest non-commented `output.file` from `.terraform-docs.yml`
+    output_file=$(grep -A1000 -e '^output:$' "$config_file" | grep ' file:' | grep -v '#' | tail -n 1 || true)
```
Comment (yermulnik) [inline hooks/terraform_docs.sh:172]: * I think `|| true` should be moved out of parenthesis to denote it is to suppress `errexit`
* Not sure whether `grep` on macOS is fully compatible with "regular" `grep` (can someone test please?), though if yes, then we can optimize cmdline
  * Also added `-m 1` to print 1st result and exit (not sure whether we indeed want to use **last** result rather than **first** — I might be wrong, though YAML doesn't allow duplicate keys I guess)
```suggestion
    output_file=$(grep -A1000 -e '^output:$' "$config_file" | grep -E -m 1 '^[[:space:]]+file:') || true
```

File: hooks/terraform_docs.sh [hunk 3]
```diff
@@ -159,13 +159,24 @@ function terraform_docs {
...
+
+    if [ "$output_file" ]; then
```
Comment (yermulnik) [inline hooks/terraform_docs.sh:174]: Bashism for consistency with other conditionals
```suggestion
    if [[ $output_file ]]; then
```

File: hooks/terraform_docs.sh [hunk 4]
```diff
@@ -159,13 +159,24 @@ function terraform_docs {
...
 
-  # Suppress terraform_docs color
   else
 
     local config_file=${args#*--config}
     config_file=${config_file#*=}
     config_file=${config_file% *}
 
+    # Prioritize `.terraform-docs.yml` `output.file` over
+    # `--hook-config=--path-to-file=` if it set
```
Comment (yermulnik) [inline hooks/terraform_docs.sh:169]: I can't seem to understand the reasoning: ain't it better raise error when both options are used instead of silently ignoring hook config's one? 🤔

Comment (yermulnik) [reply hooks/terraform_docs.sh:169]: What I mean is that if a user provides this option to hook, then the user expects it to use this option. When there's a race condition, we should raise error or indicate incorrect setting by other mean(s) (e.g. by printing warning message that the one from YAML is used and the hook config's one is ignored).
I'm ok with either approach when this is clearly brought to user's attention and knowledge.

File: hooks/terraform_docs.sh (hunk 2 above)
Comment (MaxymVlasov) [reply hooks/terraform_docs.sh:172]: YAML allow duplicate keys, and use last one

File: hooks/terraform_docs.sh (hunk 4 above)
Comment (MaxymVlasov) [reply hooks/terraform_docs.sh:169]: Reasoning was described in https://github.com/antonbabenko/pre-commit-terraform/issues/382
I'll add warning msg

Comment (yermulnik) [reply hooks/terraform_docs.sh:171]: Took a read and... and didn't get it =( I'd appreciate "tl;dr" =)
It's most common that command line parameters override config file params. Which is sort of comparable with `--hook-config`.
Either way I'm relying on your opinion in this case 👍🏻

**Review by yermulnik — APPROVED** [review]
@MaxymVlasov LGTM

File: hooks/terraform_docs.sh (hunk 4 above)
Comment (MaxymVlasov) [reply hooks/terraform_docs.sh:171]: I love removing code. Much more than write new one :D 
Because you don't need to maintain code which not exist.

At the end, I'd like to replace as much hand-made settings as possible by 3rd-party, in this case - by terraform-docs settings. So, at the end, I'd like to deprecate and remove every `--hook-config` which can be replaced by `terraform-docs` settings, as long as it will not violate main idea of how pre-commit hooks works

Comment (MaxymVlasov) [reply hooks/terraform_docs.sh:171]: So keeping this in mind, we can clearly see that native terraform-docs settings should have precedence over `--hook-config` settings, as long as they not break hook execution - in last case we try explicitly disable such settings (or at least mention in docs that they shouldn't be used)

Comment (MaxymVlasov) [reply hooks/terraform_docs.sh:171]: IE
image

**Review by MaxymVlasov — APPROVED** [review]

**Comment by antonbabenko** [comment]
This PR is included in version 1.92.2 :tada:

File: hooks/terraform_docs.sh (hunk 4 above)
Comment (yermulnik) [reply hooks/terraform_docs.sh:171]: Aha, now I think I got the point: hook config's parameter is a workaround from when tf-docs wasn't mature enough — this makes sense to me now 👍🏻 Thanks.

**Comment by sworisbreathing** [comment]
Wow thanks for fixing up the PR and the quick review/merge @yermulnik/@antonbabenko. I've just upgraded to the new release and it's working great!
