### PR TITLE
fix(WSL): Fix parallelism support for WSL systems with enabled systemd

### LINKED ISSUE #871: Incorrectly detecting wsl when systemd is enable
https://github.com/antonbabenko/pre-commit-terraform/blob/e41252b0d1a25565a38a05e7fd6b02035260f277/hooks/_common.sh#L210

Hello! I'm encountering an issue in detecting wsl and setting the cores. When systemd is enable the file is WSLInterop-late.

### PR DESCRIPTION
**Pull request by yermulnik**
Put an `x` into the box if that apply:

- [ ] This PR introduces breaking change.
- [ ] This PR fixes a bug.
- [ ] This PR adds new functionality.
- [x] This PR enhances existing functionality.

### Description of your changes

Add a version of `WSLInterop` file that exists in WSL with SystemD enabled.
Ref: https://github.com/Mozilla-Ocho/llamafile/issues/275

Fixes #871 

Or should we better use something like `grep -qi Microsoft /proc/version` (ref: https://github.com/microsoft/WSL/issues/4071) — @MaxymVlasov What do you think? 🤔

### CODE REVIEW

File: hooks/_common.sh [hunk 1]
```diff
@@ -206,8 +206,10 @@ function common::get_cpu_num {
 
   local cpu_quota cpu_period cpu_num
 
+  local wslinterop_path="/proc/sys/fs/binfmt_misc/WSLInterop"
```
Comment (MaxymVlasov) [inline hooks/_common.sh:209]: Let's make it read-only 


```suggestion
  local -r wslinterop_path="/proc/sys/fs/binfmt_misc/WSLInterop"
```

Comment (yermulnik) [reply hooks/_common.sh]: Makes sense. Thanks.

**Comment by yermulnik** [comment]
> > Or should we better use something like `grep -qi Microsoft /proc/version`
> 
> Sounds good to me too. I not sure what is faster or more relaible solution for our case. And there WSL and WSL2 - they could have different behavior

Here's how the Snapd does it: https://github.com/canonical/snapd/blob/master/release/release.go#L176-L190 — so I'm leaning to let it check whether any of these not exist: `WSLInterop`, `WSLInterop-late`, and additionally `/run/WSL` (I'm adding this third file to the bundle now).

**Review by MaxymVlasov — COMMENTED** [review]
LGTM, just let's wait confirmation from @rayppapa that it works for him

**Review by MaxymVlasov — APPROVED** [review]

**Comment by raypappa** [comment]
To follow up here as well as on the original issue. This works great for me. I added some additional information on the original issue.

**Comment by antonbabenko** [comment]
This PR is included in version 1.98.1 :tada:
