### PR TITLE
fix(`terraform_docs`): Restore `--hook-config=--add-to-existing-file` default behavior. Regression from 1.94.0.

### LINKED ISSUE #715: `terraform_docs` starting from 1.94.0 ignores `--hook-config=--add-to-existing-file=false` (our default behavior)
### Describe the bug

```
terraform-docs --output-mode="inject" --output-file=README.md md .
```
which is exactly what we run by default 
https://github.com/antonbabenko/pre-commit-terraform/blob/91b5ba0c184ca6ef14cdca0b6d3266084dbba166/hooks/terraform_docs.sh#L279

by

```yaml
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.94.2 # issue introduced in 1.94.0
    hooks:
      - id: terraform_docs
```

always updates/add `terraform-docs` section, as long as file exist.

This break your `--add-to-existing-file` setting, which by default set to `false`

### How can we reproduce it?

```bash
testdir=$(mktemp -d)
cd $testdir
touch main.tf README.md
echo "
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.94.2 # issue introduced in 1.94.0
    hooks:
      - id: terraform_docs
" > .pre-commit-config.yaml
git init
git add -A
pre-commit run
```

### Workaround
* if you on Linux (and you have no Mac users) - stick to [v1.93.1](https://github.com/antonbabenko/pre-commit-terraform/releases/tag/v1.93.1)
* otherwise, stick to [v1.92.3](https://github.com/antonbabenko/pre-commit-terraform/releases/tag/v1.92.3)

### PR DESCRIPTION
**Pull request by MaxymVlasov**
Put an `x` into the box if that apply:

- [ ] This PR introduces breaking change.
- [x] This PR fixes a bug.
- [ ] This PR adds new functionality.
- [ ] This PR enhances existing functionality.

### Description of your changes

Fixes #715

### How can we test changes

broken:
```
testdir=$(mktemp -d)
cd $testdir
touch main.tf README.md
echo "
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.94.2 # issue introduced in 1.94.0
    hooks:
      - id: terraform_docs
" > .pre-commit-config.yaml
git init
git add -A
pre-commit run
```
fixed:

```bash
testdir=$(mktemp -d)
cd $testdir
touch main.tf README.md
echo "
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: c0b1f38bae3b34f3f223bc73a8b384e2e7a766d7
    hooks:
      - id: terraform_docs
" > .pre-commit-config.yaml
git init
git add -A
pre-commit run
```

```bash
testdir=$(mktemp -d)
cd $testdir
touch main.tf README.md
echo "
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: c0b1f38bae3b34f3f223bc73a8b384e2e7a766d7
    hooks:
      - id: terraform_docs
        args:
        - --hook-config=--add-to-existing-file=true
" > .pre-commit-config.yaml
git init
git add -A
pre-commit run
```

### CODE REVIEW

File: hooks/terraform_docs.sh [hunk 1]
```diff
@@ -260,24 +260,40 @@ function terraform_docs {
...
-
-      if [ ! "$HAVE_MARKER" ]; then
-        # Use of insertion markers, where addToExisting=true, with no markers in the existing file
-        echo "$insertion_marker_begin" >> "$output_file"
-        echo "$insertion_marker_end" >> "$output_file"
-      fi
-    fi
-
     if [[ "$terraform_docs_awk_file" == "0" ]]; then
+      #? TF 0.12+ and terraform-docs 0.12.0+
```
Comment (yermulnik) [inline hooks/terraform_docs.sh:264]: Question mark is intentional? Looks a bit unclear of what it means.

File: hooks/terraform_docs.sh [hunk 2]
```diff
@@ -260,24 +260,40 @@ function terraform_docs {
...
+
+      #
+      # If `--add-to-existing-file=false` (default behavior), check is in file exist "hook markers",
+      # and if not skip execution to avoid addition of terraform-docs section -
+      # terraform-docs in 'inject' mode adds markers by default if they not present
```
Comment (yermulnik) [inline hooks/terraform_docs.sh:269]:
```suggestion
      # If `--add-to-existing-file=false` (default behavior), check if "hook markers" exist in file,
      # and, if not, skip execution to avoid addition of terraform-docs section, as
      # terraform-docs in 'inject' mode adds markers by default if they are not present
```

File: hooks/terraform_docs.sh [hunk 3]
```diff
@@ -260,24 +260,40 @@ function terraform_docs {
...
+      #
+      if ! $add_to_existing; then
```
Comment (yermulnik) [inline hooks/terraform_docs.sh:271]:
```suggestion
      if [[ $add_to_existing == false ]]; then
```

File: hooks/terraform_docs.sh [hunk 4]
```diff
@@ -260,24 +260,40 @@ function terraform_docs {
...
+        HAVE_MARKER=$(grep -o "$insertion_marker_begin" "$output_file" || exit 0)
```
Comment (yermulnik) [inline hooks/terraform_docs.sh:272]:
```suggestion
        HAVE_MARKER=$(grep -o "$insertion_marker_begin" "$output_file") || true
```

Comment (yermulnik) [reply hooks/terraform_docs.sh:272]: Out of curiosity: why are you using uppercase var name here (which is good), while in vast majority of use cases — lower case? 🤔 I'm not quite clear why this inconsistency is introduced here 🤷🏻 

Just for reference:
> The name space of environment variable names containing lowercase letters is reserved for applications. Applications can define any environment variables with names from this name space without modifying the behavior of the standard utilities.

File: hooks/terraform_docs.sh [hunk 5]
```diff
@@ -260,24 +260,40 @@ function terraform_docs {
...
+        [[ ! $HAVE_MARKER ]] && continue
```
Comment (yermulnik) [inline hooks/terraform_docs.sh:273]: Since this var is re-used in the loop, it is best to reset it (`unset HAVE_MARKER`) at the beginning of each loop iteration, so that value from previous iteration by an accident isn't re-used by next iteration(s).

File: hooks/terraform_docs.sh [hunk 6]
```diff
@@ -260,24 +260,40 @@ function terraform_docs {
...
+      fi
       # shellcheck disable=SC2086
       terraform-docs --output-mode="$output_mode" --output-file="$output_file" $tf_docs_formatter $args ./ > /dev/null
+
     else
+      #? TF 0.12+ and terraform-docs < 0.8
+      #? Yes, we don't cover case of TF 0.12+ and terraform-docs 0.8-0.11
+      #? but I portably just drop this section in next release of the hook,
```
Comment (yermulnik) [inline hooks/terraform_docs.sh:281]: Is `portably` meant to be `probably`? 🤔

File: hooks/terraform_docs.sh [hunk 7]
```diff
@@ -260,24 +260,40 @@ function terraform_docs {
...
+      #? as there no sense to support hacks for tool versions which was released more than 3 years ago
```
Comment (yermulnik) [inline hooks/terraform_docs.sh:282]:
```suggestion
      #? as there's no sense to support hacks for tool versions which were released more than 3 years ago
```

File: hooks/terraform_docs.sh [hunk 8]
```diff
@@ -260,24 +260,40 @@ function terraform_docs {
...
+
+      #
+      # If `--add-to-existing-file=true` set, check is in file exist "hook markers",
+      # and if not - append "hook markers" to the end of file.
```
Comment (yermulnik) [inline hooks/terraform_docs.sh:286]:
```suggestion
      # If `--add-to-existing-file=true` set, check if "hook markers" exist in file,
      # and, if not, append "hook markers" to the end of the file.
```

File: hooks/terraform_docs.sh [hunk 9]
```diff
@@ -260,24 +260,40 @@ function terraform_docs {
...
+      #
+      if $add_to_existing; then
```
Comment (yermulnik) [inline hooks/terraform_docs.sh:288]:
```suggestion
      if [[ $add_to_existing == true ]]; then
```

File: hooks/terraform_docs.sh [hunk 10]
```diff
@@ -260,24 +260,40 @@ function terraform_docs {
...
+        HAVE_MARKER=$(grep -o "$insertion_marker_begin" "$output_file" || exit 0)
```
Comment (yermulnik) [inline hooks/terraform_docs.sh:289]:
```suggestion
        HAVE_MARKER=$(grep -o "$insertion_marker_begin" "$output_file") || true
```

File: hooks/terraform_docs.sh [hunk 11]
```diff
@@ -260,24 +260,40 @@ function terraform_docs {
...
+
+        if [ ! "$HAVE_MARKER" ]; then
```
Comment (yermulnik) [inline hooks/terraform_docs.sh:291]:
```suggestion
        if [[ ! $HAVE_MARKER ]]; then
```

File: hooks/terraform_docs.sh [hunk 12]
```diff
@@ -260,24 +260,40 @@ function terraform_docs {
...
+          # Use of insertion markers, where addToExisting=true, with no markers in the existing file
```
Comment (yermulnik) [inline hooks/terraform_docs.sh:292]:
```suggestion
          # Use of insertion markers, when "add_to_existing=true" with no markers in the existing file
```

File: hooks/terraform_docs.sh (hunk 1 above)
Comment (MaxymVlasov) [reply hooks/terraform_docs.sh:264]: Syntax highlighting 
image
https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments

File: hooks/terraform_docs.sh (hunk 6 above)
Comment (MaxymVlasov) [reply hooks/terraform_docs.sh:281]:
```suggestion
      #? but I probably just drop this section in next release of the hook,
```

File: hooks/terraform_docs.sh (hunk 4 above)
Comment (MaxymVlasov) [reply hooks/terraform_docs.sh:272]: It is not introduced, it was here

We didn't adopt Google style guide, but I +- follow it
https://google.github.io/styleguide/shellguide.html#s7.2-variable-names

File: hooks/terraform_docs.sh (hunk 5 above)
Comment (MaxymVlasov) [reply hooks/terraform_docs.sh:273]: how it can be reused if it always set right before `if`?

Comment (MaxymVlasov) [reply hooks/terraform_docs.sh:273]: Then 

```
HAVE_MARKER=$(grep -o "$insertion_marker_begin" "$output_file" || exit 0)
```

did it for us

File: hooks/terraform_docs.sh (hunk 1 above)
Comment (yermulnik) [reply hooks/terraform_docs.sh:264]: VSCode-specific sugar?
I'm aware of `FIXME`, `TODO`, and `XXX` common keywords that are highlighted for many types of the code by variety of IDEs incl CLI editors. While it's first time is see `#?`, which is, well, is an odd sequence of chars for non-vscode users I guess 😢

File: hooks/terraform_docs.sh (hunk 4 above)
Comment (yermulnik) [reply hooks/terraform_docs.sh]: Is it constant, env var or readonly? 😲 

My point is more of this looks odd among lowercase vars that are 95% of vars in this file I guess.

File: hooks/terraform_docs.sh (hunk 5 above)
Comment (MaxymVlasov) [reply hooks/terraform_docs.sh:273]: If we add `local` to it, it will unset it on every cirlce?

Comment (yermulnik) [reply hooks/terraform_docs.sh:273]: > how it can be reused if it always set right before `if`?

believe me, people make mistakes. though it is "best to" rather than "must", so up to you to decide.

> did it for us

the `|| exit 0)` (which should be `) || true`) is to bypass `errexit`.

Comment (yermulnik) [reply hooks/terraform_docs.sh:273]: > If we add `local` to it, it will unset it on every cirlce?

I don't think so. `local` is to reduce var visibility scope.

**Review by yermulnik — APPROVED** [review]

File: hooks/terraform_docs.sh (hunk 4 above)
Comment (MaxymVlasov) [reply hooks/terraform_docs.sh]: Changed to lowercase
