### PR TITLE
feat(`terraform_providers_lock`): Fix logical issue in hook modes: Add `check-lockfile-is-cross-platform` and `regenerate-lockfile-if-some-platform-missed` modes. Last one is same as `only-check-is-current-lockfile-cross-platform`, which now is deprecated. Check README for more details

### LINKED ISSUE #949: `terraform_providers_lock` produces error when `terraform_validate` is not called before
With introduction of `mode` support to `terraform_providers_lock` hooks it should be possible to run the hook without `terraform_validate` when `mode=only-check-is-current-lockfile-cross-platform`, but it is not working as advertised.

It works as advertised only when `lockfile_contains_all_needed_sha` returns `0` = when the lock file is valid. If it NOT valid, for example it is missing hash for some platform, the condition https://github.com/antonbabenko/pre-commit-terraform/blob/cba87736ffe2c479523d9d69919c1215084c7acc/hooks/terraform_providers_lock.sh#L150 fails and code continues and runs `terraform providers lock` on line https://github.com/antonbabenko/pre-commit-terraform/blob/cba87736ffe2c479523d9d69919c1215084c7acc/hooks/terraform_providers_lock.sh#L158.

IMHO the condition could be rewritten to:

```
if [ "$mode" == "only-check-is-current-lockfile-cross-platform" ] ; then
    lockfile_contains_all_needed_sha "$platforms_count"

    exit_code=$?
    return $exit_code
  fi
```

In this case it could be executed in `mode=only-check-is-current-lockfile-cross-platform` without running `terraform_validate` which runs `terraform init` under the hood.

### PR DESCRIPTION
**Pull request by MaxymVlasov**
Put an `x` into the box if that apply:

- [ ] This PR introduces breaking change.
- [x] This PR fixes a bug.
- [x] This PR adds new functionality.
- [x] This PR enhances existing functionality.

### Description of your changes

* Logging in which folder hook failed
* Add `check-lockfile-is-cross-platform` mode, that just check is there rihgt number of SHAs for quick check.
* Rename mode `only-check-is-current-lockfile-cross-platform` to `regenerate-lockfile-if-some-platform-missed` to better describe current behavior.
* Deprecate `only-check-is-current-lockfile-cross-platform` flag
* Add validation for `--mode` flags

Fixes #949 
Related #54 
### How can we test changes

Run one by one:

```yaml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: bc820c6ddac12f731a433696575671d310d98fc1
  hooks:

    - id: terraform_providers_lock
      args:
      - --hook-config=--mode=check-lockfile-is-cross-platform
      - --args=-platform=darwin_amd64
      - --args=-platform=linux_amd64

    - id: terraform_providers_lock
      args:
      - --hook-config=--mode=regenerate-lockfile-if-some-platform-missed
      - --args=-platform=darwin_amd64
      - --args=-platform=linux_amd64

    - id: terraform_providers_lock
      args:
      - --hook-config=--mode=only-check-is-current-lockfile-cross-platform
      - --args=-platform=darwin_amd64
      - --args=-platform=linux_amd64



    - id: terraform_providers_lock
      args:
      - --hook-config=--mode=11
      - --args=-platform=darwin_amd64
      - --args=-platform=linux_amd64
```

### CODE REVIEW

File: hooks/terraform_providers_lock.sh [hunk 1]
```diff
@@ -157,8 +157,14 @@ Check migration instructions at https://github.com/antonbabenko/pre-commit-terra
   # pass the arguments to hook
   "$tf_path" providers lock "${args[@]}"
 
-  # return exit code to common::per_dir_hook
   exit_code=$?
+  if [[ $exit_code != 0 ]]; then
+    common::colorify "red" "$dir_path run failed. Detailed error above.
+Most common issue is that you didn't run requiring 'terraform init' before running this hook. It can be run by 'terraform_validate' hook - https://github.com/antonbabenko/pre-commit-terraform#terraform_validate
```
[the remark this answers is not in the document]
Comment (yermulnik) [reply hooks/terraform_providers_lock.sh]: Should the word `requiring` be `required` probably? 🤔 
Also some rewording might make sense:
```suggestion
Most common issue is that required 'terraform init' command was likely not run before running this hook. It might be run for you automatically by 'terraform_validate' hook - see https://github.com/antonbabenko/pre-commit-terraform#terraform_validate for more details
```

File: hooks/terraform_providers_lock.sh [hunk 2]
```diff
@@ -157,8 +157,14 @@ Check migration instructions at https://github.com/antonbabenko/pre-commit-terra
   # pass the arguments to hook
   "$tf_path" providers lock "${args[@]}"
 
-  # return exit code to common::per_dir_hook
   exit_code=$?
+  if [[ $exit_code != 0 ]]; then
```
Comment (yermulnik) [inline hooks/terraform_providers_lock.sh]: Arithmetic comparison should be using arithmetic operators please (if there's no strong reason to use string comparison):
```suggestion
  if [[ $exit_code -ne 0 ]]; then
```

**Review by yermulnik — APPROVED** [review]

**Review by yermulnik — APPROVED** [review]

File: hooks/terraform_providers_lock.sh [hunk 3]
```diff
@@ -144,21 +147,47 @@ Check migration instructions at https://github.com/antonbabenko/pre-commit-terra
...
+  elif [ "$mode" == "only-check-is-current-lockfile-cross-platform" ]; then
+    common::colorify "yellow" "DEPRECATION NOTICE: Flag '--mode=only-check-is-current-lockfile-cross-platform' was renamed
+  to '--mode=regenerate-lockfile-if-some-platform-missed' to better reflect its behavior. Please update your configuration.
+"
+    mode="regenerate-lockfile-if-some-platform-missed"
   fi
 
-  if [ "$mode" == "only-check-is-current-lockfile-cross-platform" ] &&
-    lockfile_contains_all_needed_sha "$platforms_count"; then
+  if [ "$mode" == "check-lockfile-is-cross-platform" ]; then
```
Comment (yermulnik) [inline hooks/terraform_providers_lock.sh]: I'd say that `case/esac` would better match the idea as opposite to multiple `if` statements. Up to you though.

File: hooks/terraform_providers_lock.sh [hunk 4]
```diff
@@ -144,21 +147,47 @@ Check migration instructions at https://github.com/antonbabenko/pre-commit-terra
...
+
+    if lockfile_contains_all_needed_sha "$platforms_count"; then
+      exit 0
+    fi
```
Comment (yermulnik) [inline hooks/terraform_providers_lock.sh]: Can be simplified to a one-liner I guess:
```suggestion
    lockfile_contains_all_needed_sha "$platforms_count" && exit 0
```

File: hooks/terraform_providers_lock.sh [hunk 5]
```diff
@@ -133,7 +135,8 @@ function per_dir_hook_unique_part {
   done
 
   # Available options:
-  #   only-check-is-current-lockfile-cross-platform (will be default)
+  #   check-lockfile-is-cross-platform (will be default)
```
Comment (yermulnik) [inline hooks/terraform_providers_lock.sh]: "will be" when? 🤔 Should it be "will be default in v2.0" instead? 🤔 
```suggestion
  #   check-lockfile-is-cross-platform (will be default in v2.0)
```

File: hooks/terraform_providers_lock.sh [hunk 6]
```diff
@@ -144,21 +147,47 @@ Check migration instructions at https://github.com/antonbabenko/pre-commit-terra
...
+  fi
+
+  if [ "$mode" == "regenerate-lockfile-if-some-platform-missed" ]; then
+
+    if lockfile_contains_all_needed_sha "$platforms_count"; then
+      exit 0
+    fi
+
+    common::colorify "yellow" "\n$dir_path/.terraform.lock.hcl missing some of required platforms.
+      All required platforms: ${platforms_names[*]}."
```
Comment (yermulnik) [inline hooks/terraform_providers_lock.sh]: I think trailing period is extraneous:
```suggestion
      All required platforms: ${platforms_names[*]}"
```

File: README.md [hunk 7]
```diff
@@ -759,26 +759,44 @@ To replicate functionality in `terraform_docs` hook:
...
 > You can check available modes for hook below.
 > </details>
 
 
-1. The hook can work in a few different modes: `only-check-is-current-lockfile-cross-platform` with and without [terraform_validate hook](#terraform_validate) and `always-regenerate-lockfile` - only with terraform_validate hook.
+1. The hook can work in a few different modes:
 
-    * `only-check-is-current-lockfile-cross-platform` without terraform_validate - only checks that lockfile has all required SHAs for all providers already added to lockfile.
+    1. <details><summary><code>--mode=check-lockfile-is-cross-platform</code> (standalone)</summary>
+        Checks that lockfile has the same amount of platform (`h1:`) checksums as specified in hook configuration. It **does not** check are these checksums are valid or that they are belongs to needed platforms.
```
Comment (yermulnik) [inline README.md]:
```suggestion
        Checks that lockfile has the same number of platform checksums (`h1:`) as requested by the hook configuration. It **does not** check whether these checksums are valid or that they match target platforms.
```

File: README.md [hunk 8]
```diff
@@ -759,26 +759,44 @@ To replicate functionality in `terraform_docs` hook:
...
-          - --hook-config=--mode=only-check-is-current-lockfile-cross-platform
+          - --hook-config=--mode=check-lockfile-is-cross-platform
         ```
 
-    * `only-check-is-current-lockfile-cross-platform` with [terraform_validate hook](#terraform_validate) - make up-to-date lockfile by adding/removing providers and only then check that lockfile has all required SHAs.
+    </details>
+
+    2. <details><summary><code>--mode=regenerate-lockfile-if-some-platform-missed</code> (standalone)</summary>
+
+        Checks that lockfile has all required SHAs for all providers already added to lockfile, and if any missed - try to add them (but could fail if `terraform init` wasn't run previously)
```
Comment (yermulnik) [inline README.md]:
```suggestion
        Checks that lockfile has checksums (`h1:`) for all requested platforms for all providers tracked by the lockfile, and if any are missed - tries to add them (but could fail if `terraform init` wasn't run previously).
```

File: README.md [hunk 9]
```diff
@@ -759,26 +759,44 @@ To replicate functionality in `terraform_docs` hook:
...
+        - id: terraform_providers_lock
+          args:
+          - --hook-config=--mode=regenerate-lockfile-if-some-platform-missed
+        ```
+
+    </details>
+
+    3. <details><summary><code>--mode=regenerate-lockfile-if-some-platform-missed</code> with <code>terraform_validate</code> hook</summary>
+
+        Make up-to-date lockfile by adding/removing providers and only then check that lockfile has all required SHAs. If any missed - adds them.
```
Comment (yermulnik) [inline README.md]:
```suggestion
        Regenerates lockfile for all required providers and checks that the lockfile tracks all required platform checksums (`h1:`) afterwards. If any are missed - adds them; superfluous providers are removed.
```

File: README.md [hunk 10]
```diff
@@ -759,26 +759,44 @@ To replicate functionality in `terraform_docs` hook:
...
 
         > **Important**
-        > Next `terraform_validate` flag requires additional dependency to be installed: `jq`. Also, it could run another slow and time consuming command - `terraform init`
+        > Next [`terraform_validate`](#terraform_validate) hook flag requires additional dependency to be installed: `jq`. Also, it could run another slow and time consuming command - `terraform init`
```
Comment (yermulnik) [inline README.md]:
```suggestion
        > The following [`terraform_validate`](#terraform_validate) hook's flag requires additional dependency to be installed: [`jq`](https://github.com/jqlang/jq). Also, it could run another slow and time consuming command - `terraform init`
```

File: README.md [hunk 11]
```diff
@@ -787,10 +805,14 @@ To replicate functionality in `terraform_docs` hook:
...
         - id: terraform_providers_lock
           args:
-          - --hook-config=--mode=only-check-is-current-lockfile-cross-platform
+          - --hook-config=--mode=regenerate-lockfile-if-some-platform-missed
         ```
 
-    * `always-regenerate-lockfile` only with [terraform_validate hook](#terraform_validate) - regenerate lockfile from scratch. Can be useful for upgrading providers in lockfile to latest versions
+    </details>
+
+    4. <details><summary><code>always-regenerate-lockfile</code> - only with terraform_validate hook.</summary>
```
Comment (yermulnik) [inline README.md]:
```suggestion
    4. <details><summary><code>always-regenerate-lockfile</code> - meant to be used only along with <code>terraform_validate</code> hook</summary>
```

File: README.md [hunk 12]
```diff
@@ -787,10 +805,14 @@ To replicate functionality in `terraform_docs` hook:
...
+
+        Regenerate lockfile from scratch. Can be useful for upgrading providers in lockfile to latest versions
```
Comment (yermulnik) [inline README.md]:
```suggestion
        Regenerates lockfile from the scratch. May be useful for upgrading providers in the lockfile to the latest versions.
```

File: hooks/terraform_providers_lock.sh [hunk 13]
```diff
@@ -146,19 +169,40 @@ Check migration instructions at https://github.com/antonbabenko/pre-commit-terra
...
+    exit 1
+  fi
+
+  if [ "$mode" == "regenerate-lockfile-if-some-platform-missed" ]; then
+
+    if lockfile_contains_all_needed_sha "$platforms_count"; then
+      exit 0
+    fi
+
+    common::colorify "yellow" "\n$dir_path/.terraform.lock.hcl missing some of required platforms.
```
Comment (MaxymVlasov) [inline hooks/terraform_providers_lock.sh]:
```suggestion
    common::colorify "yellow" "$dir_path/.terraform.lock.hcl missing some of required platforms.
```

File: hooks/terraform_providers_lock.sh [hunk 14]
```diff
@@ -146,19 +169,40 @@ Check migration instructions at https://github.com/antonbabenko/pre-commit-terra
...
+      All required platforms: ${platforms_names[*]}."
```
Comment (MaxymVlasov) [inline hooks/terraform_providers_lock.sh]:
```suggestion
      All required platforms: ${platforms_names[*]}.\n"
```

File: hooks/terraform_providers_lock.sh (hunk 4 above)
Comment (MaxymVlasov) [reply hooks/terraform_providers_lock.sh]: Yeah, I just not sure that this `exit 0` will be notable enough

File: hooks/terraform_providers_lock.sh (hunk 3 above)
Comment (MaxymVlasov) [reply hooks/terraform_providers_lock.sh]: Agree. Can you do it please?

Comment (yermulnik) [reply hooks/terraform_providers_lock.sh]: yep. gimme a whirl.

Comment (yermulnik) [reply hooks/terraform_providers_lock.sh]: e38d0fd

**Review by MaxymVlasov — COMMENTED** [review]
LGTM

**Review by yermulnik — DISMISSED** [review]
LGTM 👍🏻

**Review by yermulnik — APPROVED** [review]

**Comment by antonbabenko** [comment]
This PR is included in version 1.105.0 :tada:
